name: "Build and Push"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: ACR login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.ACR_LOGIN_URI }}
        DOCKER_USERNAME: ${{ secrets.ACR_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.ACR_CREDS }}

    - name: Restore
      run: dotnet restore
      env:
        GITHUB_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.CONTAINER_CREDS }}

    - name: Build
      run: dotnet build --no-restore --configuration Release --os linux --arch x64

    - name: Publish
      run: dotnet publish --os linux --arch x64 --configuration Release --no-build
      env:
        GITHUB_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.CONTAINER_CREDS }}

    - name: (ACR) Tag container sha
      uses: actions-hub/docker/cli@master
      with:
        args: tag whatstheweather:latest ${{ secrets.ACR_LOGIN_URI }}/whatstheweather:${{ github.sha }}

    - name: Push to ACR tagged
      uses: actions-hub/docker/cli@master
      with:
        args: push ${{ secrets.ACR_LOGIN_URI }}/whatstheweather:${{ github.sha }}

    - name: (ACR) Tag container latest
      uses: actions-hub/docker/cli@master
      with:
        args: tag whatstheweather:latest ${{ secrets.ACR_LOGIN_URI }}/whatstheweather:latest

    - name: Push to ACR latest
      uses: actions-hub/docker/cli@master
      with:
        args: push ${{ secrets.ACR_LOGIN_URI }}/whatstheweather:latest

    - name: GHCR login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.GHCR_LOGIN_URI }}
        DOCKER_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.CONTAINER_CREDS }}

    - name: (GHCR) Tag container sha
      uses: actions-hub/docker/cli@master
      with:
        args: tag whatstheweather:latest ${{ secrets.GHCR_LOGIN_URI }}/${{ secrets.CONTAINER_USERNAME }}/whatstheweather:${{ github.sha }}

    - name: Push to GHCR tagged
      uses: actions-hub/docker/cli@master
      with:
        args: push ${{ secrets.GHCR_LOGIN_URI }}/${{ secrets.CONTAINER_USERNAME }}/whatstheweather:${{ github.sha }}

    - name: (GHCR) Tag container latest
      uses: actions-hub/docker/cli@master
      with:
        args: tag whatstheweather:latest ${{ secrets.GHCR_LOGIN_URI }}/${{ secrets.CONTAINER_USERNAME }}/whatstheweather:latest

    - name: Push to GHCR latest
      uses: actions-hub/docker/cli@master
      with:
        args: push ${{ secrets.GHCR_LOGIN_URI }}/${{ secrets.CONTAINER_USERNAME }}/whatstheweather:latest