name: "Build and Push"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: GHCR login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_REGISTRY_URL: ghcr.io
        DOCKER_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.CONTAINER_CREDS }}

    - name: Restore
      run: dotnet restore
      env:
        GITHUB_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.CONTAINER_CREDS }}

    - name: Build and Publish
      run: dotnet publish --os linux --arch x64 --configuration Release 
      env:
        GITHUB_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.CONTAINER_CREDS }}

    - name: Tag container
      uses: actions-hub/docker/cli@master
      with:
        args: tag whatstheweather:latest ${{ secrets.ACR_LOGIN_URI}}/whatstheweather:latest #ghcr.io/timheuer/whatstheweather:latest

    #- name: Push to GHCR
    #  uses: actions-hub/docker/cli@master
    #  with:
    #    args: push ghcr.io/timheuer/whatstheweather:latest

    - name: ACR login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_URI }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_CREDS }}

    - name: Push to ACR
      uses: actions-hub/docker/cli@master
      with:
        args: push ${{ secrets.ACR_LOGIN_URI}}/whatstheweather:latest